# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
    vb.gui = false
end

config.vm.define "Centos01" do |c01|
  c01.vm.hostname = "lab-01"
  c01.vm.box = "centos/stream8"
  c01.vm.network :private_network, ip: "172.20.20.10"
  c01.vm.synced_folder "shared", "/opt/shared", type: "rsync"

  # Provision the c01 server with Ansible
  # c01.vm.provision :guest_ansible do |ansible|
  
  config.vm.provision 'base', type: 'ansible_local' do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.extra_vars = {ansible_python_interpreter: "/usr/bin/env python3"}
  end
 end
end