Vagrant.configure("2") do |config|
  config.vm.box_check_update = "false"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
    vb.gui = false
end

config.vm.define "Centos01" do |web|
  web.vm.hostname = "lab-01"
  web.vm.box = "centos/stream8"
  web.vm.network :private_network, ip: "172.20.20.10"
  web.vm.synced_folder "/opt/shared", "/shared"

  # Provision the webserver with Ansible
  web.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
 end
end