# -*- mode: ruby -*-
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"
  config.vbguest.auto_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
    vb.gui = false
  end

  # Enable epel repo before ansible provision.
  config.vm.provision "shell" do |shell|
    shell.path = "script.sh"
  end

  config.vm.define "Centos01", primary: true do |c01|
    c01.vm.hostname = "lab-01"
    # c01.vm.box = "centos/stream8"
    c01.vm.network :private_network, ip: "172.20.20.10"

    c01.vm.synced_folder "shared", "/opt/shared", type: "rsync",
      id: "c01", rsync__auto: true

    # Python provisioning.
    c01.vm.provision 'base', type: 'ansible_local' do |ansible|
      ansible.playbook = "ansible/c01-playbook.yml"
      # ansible.inventory_path = "inventory"
      ansible.extra_vars = {ansible_python_interpreter: "/usr/bin/env python3"}
    end
  end

  config.vm.define "Centos02" do |c02|
    c02.vm.hostname = "lab-02"
    # c02.vm.box = "centos/stream8"
    c02.vm.network :private_network, ip: "172.20.20.15"
    c02.vm.network "forwarded_port", guest: 80, host: 8080,
      auto_correct: true, id: "c02_tcp_80"

    c02.vm.synced_folder "shared", "/opt/shared", type: "rsync",
      id: "c02", rsync__auto: true

    # Core provisioning.
    c02.vm.provision 'base', type: 'ansible_local' do |ansible|
      ansible.playbook = "ansible/c02-playbook.yml"
      # ansible.inventory_path = "inventory"
      ansible.extra_vars = {ansible_python_interpreter: "/usr/bin/env python3"}
    end
  end
end

