# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  config.push.define "heroku" do |push|
    push.app = "vagrant-app"
    push.dir = "app/"
    push.remote = "development"
  end

  config.vm.box = "base"
end
