# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.base_mac = "08002712D5CB"
  config.vm.synced_folder ".", "/vagrant"
end
