# Use the Nginx image
FROM nginx:alpine

# Remove default configuration and add our custom configuration
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

# Expose the directory to link with the Unix socket
VOLUME /var/lib/tor/hidden_service/
