version: '3'
services:
  init-permissions:
    image: alpine:latest
    volumes:
      - ./domain:/var/lib/tor/hidden_service
      - ./shared:/run/app
    command: |
      sh -c "
      chown -R 100:100 /var/lib/tor/hidden_service && \
      chmod 700 /var/lib/tor/hidden_service && \
      chown -R 100:100 /run/app && \
      chmod 700 /run/app
      "
    networks:
      - internal

  tor:
    image: tor
    container_name: tor
    build: 
      context: .
      dockerfile: Dockerfile.tor
    volumes:
      - ./domain:/var/lib/tor/hidden_service
      - ./conf/torrc:/etc/tor/torrc:ro
      - ./shared:/run/app/
    networks:
      - internal
    depends_on:
      - init-permissions

  nginx:
    image: nginx
    container_name: nginx
    build: 
      context: .
      dockerfile: Dockerfile.hugo
      args:
      - HUGO_BASEURL=http://localhost:80
    volumes:
      - ./shared:/run/app/
    networks:
      - internal
    depends_on:
      - tor

networks:
  internal:
    driver: bridge
