apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    env: production
spec:
  selector: 
    matchLabels:
      env: production
  replicas: 6
  template:
    metadata:
      name: nginx
      labels:
        env: production
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m" 
        ports:
          - containerPort: 80
