# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

nodes = [
  { :hostname => 'swarm-master-1', :ip => '10.10.10.10', :ram => 1024, :cpus => 1 },
  { :hostname => 'swarm-worker-1', :ip => '10.10.10.21', :ram => 1024, :cpus => 1 },
  { :hostname => 'swarm-worker-2', :ip => '10.10.10.22', :ram => 1024, :cpus => 1 },
  { :hostname => 'ansible-1' :ip => '10.10.10.1000', :ram => 1024, :cpus => 1 }
]

Vagrant.configure("2") do |config|
  # Always use Vagrant's insecure key
  config.ssh.insert_key = false
  # Forward ssh agent to easily ssh into the different machines
  config.ssh.forward_agent = true

  # Provision swarm nodes.
  nodes.each do |node|
    config.vm.define node[:hostname] do |c02|
      c02.vm.box = "ubuntu/bionic64";
      c02.vm.hostname = node[:hostname] + ".box"
      c02.vm.network :private_network, ip: node[:ip]
      c02.vm.provider "virtualbox" do |vb|
        vb.customize [
          "modifyvm", :id, 
          "--memory", node[:ram], 
          "--cpus", node[:cpus], 
          "--hwvirtex", "on"]
      end
    end
  end
  # In addition, swarm-worker-2 is the Ansible server
  config.vm.define "ansible-1" do |ansible|
    # Provision Ansible playbook
    ansible.vm.provision "file", source: "/ansible", destination: "$HOME"
    # Install Ansible and configure nodes
    ansible.vm.provision "shell", path: "ansible.sh"
  end
end